### ISSUE TITLE
Can it support postgresql 17  docker ?

### ISSUE THREAD

**Issue by loliuy** [bjornjorgensen/Postgres-LongNameSupport#3]

**Comment by bjornjorgensen** [comment]
there https://hub.docker.com/layers/bjornjorgensen/postgres_custum/latest/images/sha256-a8a99b96669dc3892903762c544f1d8b0e0edf5951c0768bb172bac9a4cba2b6?context=repo you have an image

**Comment by bjornjorgensen** [comment]
![image](https://github.com/user-attachments/assets/49f4026e-6e6e-4dda-8d4c-3fd88410ba6b)
There is the test :)

**Comment by loliuy** [comment]
thanks
